version: '3.1'

services:

  db:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - mydata:/var/lib/mysql
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    restart: unless-stopped
    depends_on:
      - db
    environment:
     - DATABASE_HOST=db
     - PORT=$PORT
    volumes:
      - ./server:/usr/src/app
    ports:
      - "$PORT:$PORT"
    command: bash -c "./wait-for-it.sh db:3306 && npm run dev"
  front:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./client/src:/usr/share/nginx/html

volumes:
  mydata: