version: '3.1'

services:

  db:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
    volumes:
      - ./server/data/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      PORT: 8000
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8000:8000"
    command: bash -c "./wait-for-it.sh db:3306 && npm i && npm run dev"
  front:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./client/src:/usr/share/nginx/html

volumes:
  mydata: